### PR TITLE
21 place aws config

### LINKED ISSUE #21: install aws-cli, place ~/.aws/credentials
install aws-cli, place ~/.aws/credentials

### PR DESCRIPTION
**Pull request by donsizemore**
closes #21

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
@donsizemore this looks great, I think, but I'm not 100% sure what I should do to get my AWS credentials onto the EC2 instance. Here's how I was thinking of editing the docs:

```
$ git diff INSTALL.md 
diff --git a/INSTALL.md b/INSTALL.md
index 4e34982..694c428 100644
--- a/INSTALL.md
+++ b/INSTALL.md
@@ -5,7 +5,9 @@ Installing Jenkins for Dataverse
 
 This should spin up a working Jenkins installation on AWS EC2:
 
-    ec2/ec2-create-instance.sh -b develop -r https://github.com/IQSS/dataverse-jenkins.git
+    ec2/ec2-create-instance.sh -b develop -r https://github.com/IQSS/dataverse-jenkins.git -g ansible/defaults/main.yml
+
+If you would like a different configuration, terminate the instance, edit `ansible/defaults/main.yml`, and spin up a fresh instance.
 
 See below for other ways to install Jenkins.
```

Does that make sense? Edit ansible/defaults/main.yml? And just be super careful not to check in your AWS credentials?!? Or should we recommend making a copy to a different file in .gitignore?

**Comment by pdurbin** [comment]
> And just be super careful not to check in your AWS credentials?!?

Instead I'm suggesting a different approach in https://github.com/OdumInstitute/dataverse-jenkins/pull/3

Also, I ran this:

`ec2/ec2-create-instance.sh -r https://github.com/OdumInstitute/dataverse-jenkins.git -b 21_place_aws_config -g groupvars.yml`

And things are looking good. The `aws` binary has been installed. However, I'm getting this error over and over and then the job fails:

`You must specify a region. You can also configure your region by running "aws configure".`

This is puzzling to me because it looks like the region has been configured:

```
[root@ip-172-31-27-25 ~]# cat /var/lib/jenkins/.aws/config 
[default]
region = us-east-1
```

Here's a screenshot of the error from http://ec2-54-144-84-196.compute-1.amazonaws.com:8080/job/IQSS-Dataverse-Develop/1/console with more context:

Screen Shot 2019-11-06 at 11 00 50 AM

**Comment by donsizemore** [comment]
@pdurbin weird. i thought secrets went in credentials, config went in config. i'll tell ansible to write the region setting to both.

**Comment by pdurbin** [comment]
@donsizemore no, I think you're doing it right. I don't understand why I'm seeing the behavior I'm seeing. 😕

**Comment by pdurbin** [comment]
@donsizemore I just merged this because it's probably close enough to what I need and I don't want it on the board while I'm out tomorrow. Thanks! I'll open a fresh issue if I'm still having trouble. 😄

**Pull request merged**
