### PR TITLE
update IQSS-Dataverse-Develop.xml

### PR DESCRIPTION
**Pull request by donsizemore**
document somewhat satisfactory EC2 workflow

### CODE REVIEW

**Comment by pdurbin** [comment]
At "talk after" standup @djbrooke agreed that it would be good for us to try this out. I'm blocked on testing by #19 so I'll sort that out first and then circle back to this pull request.

I'd also like to note that once we get this pull request merged, it should be a fix for both #3 and #4, which is awesome.

**Comment by pdurbin** [comment]
I'm using ./import-job.sh to import the job and it's *mostly* working. Here's a screenshot:

IQSS-dataverse-develop_Config_ Jenkins _-_2019-10-16_14 01 28

Not that I'm getting some of the good stuff in this pull request such as "start with a clean plate" but I don't seem to be getting other good stuff (screenshot below) like "create ec2 instance".

Screen Shot 2019-10-16 at 2 03 49 PM

I ran import-job.sh as "centos" if that matters. I could try again as the root user.

**Comment by donsizemore** [comment]
@pdurbin XML import failure? Here's the rest of the job... same as IQSS-Dataverse-Develop

Screen Shot 2019-10-16 at 14 09 15
Screen Shot 2019-10-16 at 14 09 32

**Comment by pdurbin** [comment]
@donsizemore thanks, this is what I'm seeing (more stuff but apparently not all of it, no ec2?) after installing the import plugin (I added some more docs in 937a26e):

IQSS-dataverse-develop_Config_ Jenkins _-_2019-10-16_14 50 30

**Comment by donsizemore** [comment]
Okay, so we need to add the import plugin and the PostBuildScript plugin.

**Comment by pdurbin** [comment]
@donsizemore sounds good. I'll terminate my Jenkins instance and as we discussed in IRC, we'll pick this up later, maybe next week. Thanks!

**Pull request closed without merging**
