### PR TITLE
#27 update IQSS-Dataverse-Develop job config to add JaCoCo

### PR DESCRIPTION
**Pull request by donsizemore**
updates IQSS-Dataverse-Develop.xml

### CODE REVIEW

**Review by pdurbin — COMMENTED** [review]
@djbrooke can you please take a look at this. I believe this moves us from a t2.medium to a t2.xlarge so the Amazon bill will be higher. Thanks.

**Review by djbrooke — APPROVED** [review]
Thanks @donsizemore and thanks @pdurbin for the tag. This increase is fine for now. We should revisit once we move to Payara.

**Comment by djbrooke** [comment]
@donsizemore feel free to merge this!

**Comment by donsizemore** [comment]
> I believe this moves us from a t2.medium to a t2.xlarge so the Amazon bill will be higher.

Correct: the API test suite was failing on t2.medium and t2.large.

**Pull request merged**
